[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  YARN_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn dev"
  port = 5173
  publish = "dist"
